name: 'HostlocAutoGetPoints'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests pyaes
    - name: 'Get points'
      env:
        HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
        HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
        BOT_API: ${{ secrets.BOT_API }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python HostlocGetPoints.py
